"""Type definitions for BSH Engine SDK"""
from .response import BshResponse, BshError, is_ok
from .search import (
    BshSearch,
    Filter,
    GroupBy,
    Aggregate,
    Sort,
    Pagination,
    LogicalOperator,
    ComparisonOperator,
    AggregateFunction,
)
from .auth import AuthToken, LoginParams, AuthTokens
from .core import (
    BshUser,
    BshUserInit,
    BshEntities,
    BshSchemas,
    BshTypes,
    BshPolicy,
    BshRole,
    BshEmailTemplate,
    BshEventLogs,
    SentEmail,
    BshTrigger,
    BshTriggerInstance,
    BshFiles,
    BshConfigurations,
    BshSettings,
    BshApiKeys,
    BshApiKeysForm,
    UploadResponse,
    UploadOptions,
    MailingPayload,
    CacheInfo,
    BshTriggerPlugin,
    BshTriggerAction,
)

__all__ = [
    "BshResponse",
    "BshError",
    "is_ok",
    "BshSearch",
    "Filter",
    "GroupBy",
    "Aggregate",
    "Sort",
    "Pagination",
    "LogicalOperator",
    "ComparisonOperator",
    "AggregateFunction",
    "AuthToken",
    "LoginParams",
    "AuthTokens",
    "BshUser",
    "BshUserInit",
    "BshEntities",
    "BshSchemas",
    "BshTypes",
    "BshPolicy",
    "BshRole",
    "BshEmailTemplate",
    "BshEventLogs",
    "SentEmail",
    "BshTrigger",
    "BshTriggerInstance",
    "BshFiles",
    "BshConfigurations",
    "BshSettings",
    "BshApiKeys",
    "BshApiKeysForm",
    "UploadResponse",
    "UploadOptions",
    "MailingPayload",
    "CacheInfo",
    "BshTriggerPlugin",
    "BshTriggerAction",
]

